using System;

// Pyramid.Run();
// Square.Run();
// Temp.Run();
// Key.Run();
// British.Run();
// CopyArray.Run();
// ArraySwap.Run();
// FindingTheSameValues.Run();
// CountingTheSameValues.Run();
// ReturningAnArray.Run();
// CombiningTwoArraysIntoOne.Run();
// SortingAnArray.Run();
// FindingDuplicateElements.Run();
// FindingAnArrayInAnArray.Run();
// ArithmeticMeanOfTheArray.Run();
// FindingMatchesInAnArray.Run();
// FindingMismatchesInAnArray.Run();
// AlternatelyWritingArrayValues.Run();
// WriteAnArrayToAShuffle.Run();
// WriteTheLargestNumbersToAnArray.Run();
// Key.Run();
WriteValuesGreaterThanTheSpecifiedValue.Run();